rootProject.name = "MoonLightBridge"

include(":java:moonlight-bridge-client")
include(":java:moonlight-bridge-java")
include(":java:moonlight-bridge-paper")
include(":java:moonlight-bridge-sentry")
include(":java:moonlight-bridge-framework")
include(":java:moonlight-bridge-example-api")
include(":java:moonlight-bridge-gradle-plugin")
include(":java:moonlight-bridge-code-first")
include(":java:moonlight-bridge-otel")
include(":java:moonlight-bridge-micrometer")
include(":examples:paper-test-plugin")
include(":examples:paper-load-test-plugin")
include(":examples:observability-client")
include(":examples:kotlin-code-first-contract")
