[package]
name = "moonlight-bridge-test-plugin-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
moonlight-bridge-server = { path = "../../crates/moonlight-bridge-server" }
moonlight-bridge-sentry = { path = "../../crates/moonlight-bridge-sentry" }
moonlight-bridge-example-api = { path = "../../crates/moonlight-bridge-example-api" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
