[package]
name = "moonlight-bridge-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
description = "High-throughput Tokio RPC server for MoonLightBridge"
documentation = "https://docs.rs/moonlight-bridge-server"
publish = ["crates-io"]

[dependencies]
moonlight-bridge-protocol = { version = "0.1.1", path = "../moonlight-bridge-protocol" }
tokio.workspace = true
tokio-rustls.workspace = true
rustls-pemfile.workspace = true
tracing.workspace = true
