[package]
name = "moonlight-bridge-example-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
moonlight-bridge-protocol = { version = "0.1.1", path = "../moonlight-bridge-protocol" }
moonlight-bridge-server = { version = "0.1.1", path = "../moonlight-bridge-server" }
prost.workspace = true

[dev-dependencies]
moonlight-bridge-codegen = { version = "0.1.1", path = "../moonlight-bridge-codegen" }

[build-dependencies]
prost-build.workspace = true
moonlight-bridge-codegen = { version = "0.1.1", path = "../moonlight-bridge-codegen" }
