[package]
name = "moonlight-bridge-observability-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
moonlight-bridge-protocol = { path = "../../crates/moonlight-bridge-protocol" }
moonlight-bridge-server = { path = "../../crates/moonlight-bridge-server" }
moonlight-bridge-observability = { path = "../../crates/moonlight-bridge-observability", features = ["prometheus", "otel", "otlp"] }
opentelemetry.workspace = true
prost.workspace = true
tokio.workspace = true

[build-dependencies]
moonlight-bridge-codegen = { path = "../../crates/moonlight-bridge-codegen" }
prost-build.workspace = true
