use prost::Message;
use prost_types::{FileDescriptorProto, FileDescriptorSet, MethodDescriptorProto};
use std::{
    collections::{HashMap, HashSet},
    fmt::Write as _,
    fs, io,
    path::Path,
};

pub mod schema;

pub fn generate_rust(
    descriptor_path: impl AsRef<Path>,
    output: impl AsRef<Path>,
) -> io::Result<()> {
    let descriptor = read_descriptor(descriptor_path)?;
    validate_method_ids(&descriptor)?;
    let mut code = String::from(
        "// Generated by moonlight-bridge-codegen. Do not edit.\n\
         use moonlight_bridge_protocol::ErrorCode;\n\
         use moonlight_bridge_server::{HandlerError, RouterBuilder};\n\
         use prost::Message;\n\
         use std::{future::Future, sync::Arc};\n\n",
    );

    for file in &descriptor.file {
        for service in &file.service {
            let service_name = required(&service.name, "service name")?;
            writeln!(code, "pub trait {service_name}: Send + Sync + 'static {{").unwrap();
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let rust_method = snake_case(method_name);
                let input = rust_message_type(method.input_type.as_deref())?;
                let output = rust_message_type(method.output_type.as_deref())?;
                writeln!(code, "    fn {rust_method}(&self, request: crate::model::{input}) -> impl Future<Output = Result<crate::model::{output}, HandlerError>> + Send;").unwrap();
            }
            writeln!(code, "}}\n").unwrap();

            let register_name = format!("register_{}", snake_case(service_name));
            writeln!(code, "pub fn {register_name}<S>(mut builder: RouterBuilder, service: Arc<S>) -> RouterBuilder where S: {service_name} {{").unwrap();
            for method in &service.method {
                generate_rust_method(&mut code, file, service_name, method)?;
            }
            writeln!(code, "    builder\n}}\n").unwrap();
        }
    }
    fs::write(output, code)
}

pub fn generate_java(
    descriptor_path: impl AsRef<Path>,
    output_root: impl AsRef<Path>,
) -> io::Result<()> {
    let descriptor = read_descriptor(descriptor_path)?;
    validate_method_ids(&descriptor)?;
    let java_types = java_type_map(&descriptor)?;

    for file in &descriptor.file {
        let package = java_package(file)?;
        let directory = output_root.as_ref().join(package.replace('.', "/"));
        fs::create_dir_all(&directory)?;
        for service in &file.service {
            let service_name = required(&service.name, "service name")?;
            let class_name = format!("{service_name}Client");
            let mut code = format!(
                "// Generated by moonlight-bridge-codegen. Do not edit.\npackage {package};\n\n\
                 import ru.moonlightproject.bridge.client.MoonLightChannel;\n\
                 import ru.moonlightproject.bridge.client.MoonLightRequest;\n\
                 import java.time.Duration;\n\
                 import java.util.ArrayList;\n\
                 import java.util.List;\n\
                 import java.util.Objects;\n\
                 import java.util.concurrent.CompletableFuture;\n\
                 import java.util.concurrent.CompletionException;\n\n\
                 public final class {class_name} {{\n\
                 private final MoonLightChannel channel;\n\
                 private final Duration deadline;\n\n\
                 public {class_name}(MoonLightChannel channel) {{ this(channel, Duration.ofSeconds(2)); }}\n\
                 private {class_name}(MoonLightChannel channel, Duration deadline) {{\n\
                 this.channel = Objects.requireNonNull(channel);\n\
                 this.deadline = Objects.requireNonNull(deadline);\n\
                 }}\n\
                 public {class_name} withDeadline(Duration deadline) {{ return new {class_name}(channel, deadline); }}\n\n"
            );
            for method in &service.method {
                generate_java_method(&mut code, file, service_name, method, &java_types)?;
            }
            code.push_str("}\n");
            fs::write(directory.join(format!("{class_name}.java")), code)?;
        }
    }
    Ok(())
}

fn generate_rust_method(
    code: &mut String,
    file: &FileDescriptorProto,
    service: &str,
    method: &MethodDescriptorProto,
) -> io::Result<()> {
    reject_streaming(method)?;
    let method_name = required(&method.name, "method name")?;
    let rust_method = snake_case(method_name);
    let input = rust_message_type(method.input_type.as_deref())?;
    let canonical = canonical_method(file, service, method_name);
    let id = method_id(&canonical);
    writeln!(
        code,
        "    builder = builder.route(0x{id:08X}, move |body| {{"
    )
    .unwrap();
    writeln!(code, "        let service = service.clone();").unwrap();
    writeln!(code, "        async move {{").unwrap();
    writeln!(code, "            let request = crate::model::{input}::decode(body.as_slice()).map_err(|error| HandlerError::new(ErrorCode::InvalidRequest, error.to_string()))?;").unwrap();
    writeln!(
        code,
        "            let response = service.{rust_method}(request).await?;"
    )
    .unwrap();
    writeln!(code, "            Ok(response.encode_to_vec())").unwrap();
    writeln!(code, "        }}").unwrap();
    writeln!(code, "    }});").unwrap();
    Ok(())
}

fn generate_java_method(
    code: &mut String,
    file: &FileDescriptorProto,
    service: &str,
    method: &MethodDescriptorProto,
    types: &HashMap<String, String>,
) -> io::Result<()> {
    reject_streaming(method)?;
    let name = required(&method.name, "method name")?;
    let input_key = required(&method.input_type, "input type")?;
    let output_key = required(&method.output_type, "output type")?;
    let input = types
        .get(input_key)
        .ok_or_else(|| invalid(format!("unknown input type {input_key}")))?;
    let output = types
        .get(output_key)
        .ok_or_else(|| invalid(format!("unknown output type {output_key}")))?;
    let canonical = canonical_method(file, service, name);
    let id = method_id(&canonical);
    let java_method = lower_camel(name);
    writeln!(
        code,
        "public static final int {}_METHOD_ID = 0x{id:08X};",
        upper_snake(name)
    )
    .unwrap();
    writeln!(
        code,
        "public CompletableFuture<{output}> {java_method}({input} request) {{"
    )
    .unwrap();
    writeln!(code, "    return channel.request({}_METHOD_ID, request.toByteArray(), deadline).thenApply(body -> {{", upper_snake(name)).unwrap();
    writeln!(code, "        try {{ return {output}.parseFrom(body); }}").unwrap();
    writeln!(code, "        catch (com.google.protobuf.InvalidProtocolBufferException error) {{ throw new CompletionException(error); }}").unwrap();
    writeln!(code, "    }});").unwrap();
    writeln!(code, "}}\n").unwrap();
    writeln!(
        code,
        "public CompletableFuture<List<{output}>> {java_method}Batch(List<{input}> requests) {{"
    )
    .unwrap();
    writeln!(code, "    List<MoonLightRequest> calls = requests.stream().map(request -> new MoonLightRequest({}_METHOD_ID, request.toByteArray(), deadline)).toList();", upper_snake(name)).unwrap();
    writeln!(
        code,
        "    return channel.requestBatch(calls).thenApply(payloads -> {{"
    )
    .unwrap();
    writeln!(
        code,
        "        List<{output}> responses = new ArrayList<>(payloads.size());"
    )
    .unwrap();
    writeln!(code, "        for (byte[] body : payloads) {{").unwrap();
    writeln!(
        code,
        "            try {{ responses.add({output}.parseFrom(body)); }}"
    )
    .unwrap();
    writeln!(code, "            catch (com.google.protobuf.InvalidProtocolBufferException error) {{ throw new CompletionException(error); }}").unwrap();
    writeln!(code, "        }}").unwrap();
    writeln!(code, "        return List.copyOf(responses);").unwrap();
    writeln!(code, "    }});").unwrap();
    writeln!(code, "}}\n").unwrap();
    Ok(())
}

fn read_descriptor(path: impl AsRef<Path>) -> io::Result<FileDescriptorSet> {
    FileDescriptorSet::decode(fs::read(path)?.as_slice()).map_err(invalid)
}

fn validate_method_ids(descriptor: &FileDescriptorSet) -> io::Result<()> {
    let mut ids = HashSet::new();
    for file in &descriptor.file {
        for service in &file.service {
            let service_name = required(&service.name, "service name")?;
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let canonical = canonical_method(file, service_name, method_name);
                let id = method_id(&canonical);
                if !ids.insert(id) {
                    return Err(invalid(format!(
                        "method ID collision at {canonical}: 0x{id:08X}"
                    )));
                }
            }
        }
    }
    Ok(())
}

fn java_type_map(descriptor: &FileDescriptorSet) -> io::Result<HashMap<String, String>> {
    let mut result = HashMap::new();
    for file in &descriptor.file {
        let proto_package = file.package.as_deref().unwrap_or("");
        let java_package = java_package(file)?;
        for message in &file.message_type {
            let name = required(&message.name, "message name")?;
            result.insert(
                format!(".{proto_package}.{name}"),
                format!("{java_package}.{name}"),
            );
        }
    }
    Ok(result)
}

fn java_package(file: &FileDescriptorProto) -> io::Result<String> {
    if let Some(package) = file
        .options
        .as_ref()
        .and_then(|options| options.java_package.clone())
    {
        return Ok(package);
    }
    Ok(required(&file.package, "proto package")?.to_owned())
}

fn canonical_method(file: &FileDescriptorProto, service: &str, method: &str) -> String {
    let package = file.package.as_deref().unwrap_or("");
    if package.is_empty() {
        format!("{service}/{method}")
    } else {
        format!("{package}.{service}/{method}")
    }
}

pub const fn method_id(name: &str) -> u32 {
    let bytes = name.as_bytes();
    let mut hash = 0x811C_9DC5u32;
    let mut index = 0;
    while index < bytes.len() {
        hash ^= bytes[index] as u32;
        hash = hash.wrapping_mul(0x0100_0193);
        index += 1;
    }
    hash
}

fn rust_message_type(value: Option<&str>) -> io::Result<&str> {
    value
        .ok_or_else(|| invalid("missing message type"))?
        .rsplit('.')
        .next()
        .ok_or_else(|| invalid("invalid message type"))
}

fn reject_streaming(method: &MethodDescriptorProto) -> io::Result<()> {
    if method.client_streaming.unwrap_or(false) || method.server_streaming.unwrap_or(false) {
        return Err(invalid("streaming methods are not supported yet"));
    }
    Ok(())
}

fn required<'a>(value: &'a Option<String>, field: &str) -> io::Result<&'a str> {
    value
        .as_deref()
        .ok_or_else(|| invalid(format!("missing {field}")))
}

fn snake_case(value: &str) -> String {
    let mut result = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch.is_uppercase() && index > 0 {
            result.push('_');
        }
        result.extend(ch.to_lowercase());
    }
    result
}

fn upper_snake(value: &str) -> String {
    snake_case(value).to_uppercase()
}

fn lower_camel(value: &str) -> String {
    let mut chars = value.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_lowercase().chain(chars).collect()
    })
}

fn invalid(error: impl std::fmt::Display) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn method_ids_are_deterministic() {
        assert_eq!(
            method_id("moonlight.bridge.example.v1.EchoService/Echo"),
            0x237D_FACC
        );
    }

    #[test]
    fn generated_names_follow_language_conventions() {
        assert_eq!(snake_case("GetPlayerData"), "get_player_data");
        assert_eq!(lower_camel("GetPlayerData"), "getPlayerData");
        assert_eq!(upper_snake("GetPlayerData"), "GET_PLAYER_DATA");
    }
}
