#![doc = include_str!("../README.md")]

use prost::Message;
use prost_types::{FileDescriptorProto, FileDescriptorSet, MethodDescriptorProto};
use std::{
    collections::{HashMap, HashSet},
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

mod policy;
/// Schema-lock creation and backward-compatibility validation.
pub mod schema;

pub use policy::{CompressionMode, Idempotency, RetryPolicy, RpcPolicy, descriptor_policies};

/// Complete Cargo build-script configuration for models, compatibility checks and bindings.
pub struct RustBuildConfig {
    /// Protobuf source files passed to `prost-build`.
    pub protos: Vec<PathBuf>,
    /// Import roots used to resolve Protobuf imports.
    pub includes: Vec<PathBuf>,
    /// Compatibility baseline checked during the build.
    pub schema_lock: PathBuf,
    /// Filename written into Cargo's `OUT_DIR` for generated service bindings.
    pub generated_services_name: String,
}

/// Runs the complete Rust generation pipeline and returns the generated service source path.
pub fn compile_rust_api(config: RustBuildConfig) -> Result<PathBuf, Box<dyn std::error::Error>> {
    for path in config
        .protos
        .iter()
        .chain(std::iter::once(&config.schema_lock))
    {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    for include in &config.includes {
        let options = include.join("moonlight/bridge/options/v1/options.proto");
        if options.is_file() {
            println!("cargo:rerun-if-changed={}", options.display());
        }
    }
    let output = PathBuf::from(std::env::var("OUT_DIR")?);
    let descriptor = output.join("moonlight-bridge-descriptor.pb");
    let generated = output.join(config.generated_services_name);
    let mut prost = prost_build::Config::new();
    prost.file_descriptor_set_path(&descriptor);
    prost.compile_protos(&config.protos, &config.includes)?;
    schema::check_lock(&descriptor, &config.schema_lock)?;
    generate_rust(&descriptor, &generated)?;
    Ok(generated)
}

/// Generates Rust service traits, registrations, and event publishers from descriptors.
pub fn generate_rust(
    descriptor_path: impl AsRef<Path>,
    output: impl AsRef<Path>,
) -> io::Result<()> {
    let descriptor_path = descriptor_path.as_ref();
    let descriptor = read_descriptor(descriptor_path)?;
    let policies = descriptor_policies(descriptor_path)?;
    validate_method_ids(&descriptor)?;
    let has_server_streaming = descriptor
        .file
        .iter()
        .flat_map(|file| &file.service)
        .flat_map(|service| &service.method)
        .any(|method| method.server_streaming.unwrap_or(false));
    let mut code = String::from(
        "// Generated by moonlight-bridge-codegen. Do not edit.\n\
         use moonlight_bridge_protocol::ErrorCode;\n\
         use moonlight_bridge_server::{EventHub, HandlerError, RouterBuilder, trace_async_function, trace_function};\n\
         use prost::Message;\n\
         use std::{future::Future, sync::Arc};\n\n",
    );
    if has_server_streaming {
        code.push_str("use moonlight_bridge_server::{ServerStream, try_map_server_stream};\n\n");
    }
    code.push_str(
        r#"/// Retry safety compiled from a Protobuf RPC policy.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RpcIdempotency {
    /// No retry-safety declaration.
    Unspecified,
    /// Read-only operation.
    ReadOnly,
    /// Repetition has the same effect.
    Idempotent,
    /// Every attempt requires one stable key.
    KeyRequired,
}

/// Compression behavior compiled from a Protobuf RPC policy.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RpcCompression {
    /// Use the runtime default.
    Default,
    /// Disable payload compression.
    Disabled,
    /// Compress when useful.
    Prefer,
    /// Require negotiated compression.
    Required,
}

/// Immutable generated policy for one RPC method.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RpcPolicy {
    /// Overall logical-call timeout.
    pub timeout_ms: u32,
    /// Stream idle timeout, or zero for unary methods.
    pub idle_timeout_ms: u32,
    /// Total attempts including the initial call.
    pub max_attempts: u32,
    /// Delay before the first retry.
    pub initial_backoff_ms: u32,
    /// Maximum retry delay.
    pub max_backoff_ms: u32,
    /// Backoff multiplier in thousandths.
    pub backoff_multiplier_milli: u32,
    /// Retry-safety classification.
    pub idempotency: RpcIdempotency,
    /// Maximum decoded request bytes.
    pub max_request_bytes: u32,
    /// Maximum decoded response bytes.
    pub max_response_bytes: u32,
    /// Authorization scopes required by middleware.
    pub required_scopes: &'static [&'static str],
    /// Per-method compression behavior.
    pub compression: RpcCompression,
    /// Trace sampling probability in millionths.
    pub trace_sample_per_million: u32,
}

"#,
    );

    for file in &descriptor.file {
        for service in &file.service {
            let service_name = required(&service.name, "service name")?;
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let canonical = canonical_method(file, service_name, method_name);
                let policy = policies
                    .get(&canonical)
                    .ok_or_else(|| invalid(format!("missing policy for {canonical}")))?;
                generate_rust_policy_constant(&mut code, service_name, method_name, policy);
            }
            writeln!(
                code,
                "/// Typed implementation of the `{service_name}` Protobuf service."
            )
            .unwrap();
            writeln!(code, "pub trait {service_name}: Send + Sync + 'static {{").unwrap();
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let rust_method = snake_case(method_name);
                let input = rust_message_type(method.input_type.as_deref())?;
                let output = rust_message_type(method.output_type.as_deref())?;
                writeln!(code, "    /// Handles the `{method_name}` RPC.").unwrap();
                if method.client_streaming.unwrap_or(false) {
                    return Err(invalid(
                        "client and bidirectional streaming are not supported yet",
                    ));
                }
                if method.server_streaming.unwrap_or(false) {
                    writeln!(code, "    fn {rust_method}(&self, request: crate::model::{input}) -> impl Future<Output = Result<ServerStream<crate::model::{output}>, HandlerError>> + Send;").unwrap();
                } else {
                    writeln!(code, "    fn {rust_method}(&self, request: crate::model::{input}) -> impl Future<Output = Result<crate::model::{output}, HandlerError>> + Send;").unwrap();
                }
            }
            writeln!(code, "}}\n").unwrap();

            let register_name = format!("register_{}", snake_case(service_name));
            writeln!(
                code,
                "/// Registers every `{service_name}` RPC handler on a router builder."
            )
            .unwrap();
            writeln!(code, "pub fn {register_name}<S>(mut builder: RouterBuilder, service: Arc<S>) -> RouterBuilder where S: {service_name} {{").unwrap();
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let canonical = canonical_method(file, service_name, method_name);
                let policy = policies
                    .get(&canonical)
                    .ok_or_else(|| invalid(format!("missing policy for {canonical}")))?;
                generate_rust_method(&mut code, file, service_name, method, policy)?;
            }
            writeln!(code, "    builder\n}}\n").unwrap();
        }
        for message in &file.message_type {
            let name = required(&message.name, "message name")?;
            if name.ends_with("Event") {
                let id = method_id(&canonical_event(file, name));
                writeln!(
                    code,
                    "/// Stable wire ID of the `{name}` event.\npub const {}_ID: u32 = 0x{id:08X};",
                    upper_snake(name)
                )
                .unwrap();
                writeln!(
                    code,
                    "/// Publishes a `{name}` event and returns the number of active receivers.\npub fn publish_{}(events: &EventHub, event: crate::model::{name}) -> usize {{",
                    snake_case(name)
                )
                .unwrap();
                writeln!(
                    code,
                    "    events.publish({}_ID, event.encode_to_vec())",
                    upper_snake(name)
                )
                .unwrap();
                writeln!(code, "}}\n").unwrap();
            }
        }
    }
    fs::write(output, code)
}

/// Generates Java asynchronous clients and typed event helpers from descriptors.
pub fn generate_java(
    descriptor_path: impl AsRef<Path>,
    output_root: impl AsRef<Path>,
) -> io::Result<()> {
    let descriptor_path = descriptor_path.as_ref();
    let descriptor = read_descriptor(descriptor_path)?;
    let policies = descriptor_policies(descriptor_path)?;
    validate_method_ids(&descriptor)?;
    let java_types = java_type_map(&descriptor)?;

    for file in &descriptor.file {
        let package = java_package(file)?;
        let directory = output_root.as_ref().join(package.replace('.', "/"));
        fs::create_dir_all(&directory)?;
        for service in &file.service {
            let service_name = required(&service.name, "service name")?;
            let class_name = format!("{service_name}Client");
            let mut code = format!(
                "// Generated by moonlight-bridge-codegen. Do not edit.\npackage {package};\n\n\
                 import ru.moonlightproject.bridge.client.MoonLightChannel;\n\
                 import ru.moonlightproject.bridge.client.MoonLightRequest;\n\
                 import ru.moonlightproject.bridge.client.MoonLightTelemetry;\n\
                 import ru.moonlightproject.bridge.client.MoonLightStreams;\n\
                 import ru.moonlightproject.bridge.client.RpcPolicy;\n\
                 import java.time.Duration;\n\
                 import java.util.ArrayList;\n\
                 import java.util.List;\n\
                 import java.util.Objects;\n\
                 import java.util.Set;\n\
                 import java.util.concurrent.CompletableFuture;\n\
                 import java.util.concurrent.CompletionException;\n\
                 import java.util.concurrent.Flow;\n\n\
                 /** Asynchronous typed client for the {{@code {service_name}}} Protobuf service. */\n\
                 public final class {class_name} {{\n\
                 private final MoonLightChannel channel;\n\
                 private final Duration deadlineLimit;\n\n\
                 /** Creates a client using each method's generated deadline. */\n\
                 public {class_name}(MoonLightChannel channel) {{ this(channel, null); }}\n\
                 private {class_name}(MoonLightChannel channel, Duration deadlineLimit) {{\n\
                 this.channel = Objects.requireNonNull(channel);\n\
                 this.deadlineLimit = deadlineLimit;\n\
                 }}\n\
                 /** Returns a view that may tighten but never extend generated method deadlines. */\n\
                 public {class_name} withDeadline(Duration deadline) {{\n\
                 Objects.requireNonNull(deadline);\n\
                 if (deadline.isZero() || deadline.isNegative()) throw new IllegalArgumentException(\"deadline must be positive\");\n\
                 return new {class_name}(channel, deadline);\n\
                 }}\n\n"
            );
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let canonical = canonical_method(file, service_name, method_name);
                let policy = policies
                    .get(&canonical)
                    .ok_or_else(|| invalid(format!("missing policy for {canonical}")))?;
                generate_java_method(&mut code, file, service_name, method, &java_types, policy)?;
            }
            code.push_str("}\n");
            fs::write(directory.join(format!("{class_name}.java")), code)?;
        }
        let event_messages: Vec<_> = file
            .message_type
            .iter()
            .filter(|message| {
                message
                    .name
                    .as_deref()
                    .is_some_and(|name| name.ends_with("Event"))
            })
            .collect();
        if !event_messages.is_empty() {
            let file_name = required(&file.name, "proto file name")?;
            let stem = Path::new(file_name)
                .file_stem()
                .and_then(|stem| stem.to_str())
                .ok_or_else(|| invalid("invalid proto file name"))?;
            let class_name = format!("{}Events", upper_camel_words(stem));
            let mut code = format!(
                "// Generated by moonlight-bridge-codegen. Do not edit.\npackage {package};\n\n\
                 import ru.moonlightproject.bridge.client.MoonLightChannel;\n\
                 import java.util.concurrent.CompletionException;\n\
                 import java.util.concurrent.Flow;\n\
                 import java.util.function.Consumer;\n\n\
                 /** Typed subscriptions for events declared in {{@code {file_name}}}. */\n\
                 public final class {class_name} {{\n\
                 private {class_name}() {{ }}\n\n"
            );
            for message in event_messages {
                let name = required(&message.name, "message name")?;
                let id = method_id(&canonical_event(file, name));
                writeln!(
                    code,
                    "/** Stable wire ID of the {{@code {name}}} event. */\npublic static final int {}_ID = 0x{id:08X};",
                    upper_snake(name)
                )
                .unwrap();
                writeln!(
                    code,
                    "/** Subscribes to {{@code {name}}} events; close the result to unsubscribe. */"
                )
                .unwrap();
                writeln!(code, "public static AutoCloseable on{name}(MoonLightChannel channel, Consumer<{name}> listener) {{").unwrap();
                writeln!(
                    code,
                    "    return channel.subscribe({}_ID, body -> {{",
                    upper_snake(name)
                )
                .unwrap();
                writeln!(
                    code,
                    "        try {{ listener.accept({name}.parseFrom(body)); }}"
                )
                .unwrap();
                writeln!(code, "        catch (com.google.protobuf.InvalidProtocolBufferException error) {{ throw new CompletionException(error); }}").unwrap();
                writeln!(code, "    }});").unwrap();
                writeln!(code, "}}\n").unwrap();
            }
            code.push_str("}\n");
            fs::write(directory.join(format!("{class_name}.java")), code)?;
        }
    }
    Ok(())
}

fn generate_rust_method(
    code: &mut String,
    file: &FileDescriptorProto,
    service: &str,
    method: &MethodDescriptorProto,
    _policy: &RpcPolicy,
) -> io::Result<()> {
    reject_unsupported_streaming(method)?;
    let method_name = required(&method.name, "method name")?;
    let rust_method = snake_case(method_name);
    let input = rust_message_type(method.input_type.as_deref())?;
    let canonical = canonical_method(file, service, method_name);
    let id = method_id(&canonical);
    let policy_name = rust_policy_name(service, method_name);
    let route = if method.server_streaming.unwrap_or(false) {
        "route_stream_scoped"
    } else {
        "route_scoped"
    };
    writeln!(code, "    let {rust_method}_service = service.clone();").unwrap();
    writeln!(
        code,
        "    builder = builder.{route}(0x{id:08X}, {policy_name}.required_scopes, move |body| {{"
    )
    .unwrap();
    writeln!(code, "        let service = {rust_method}_service.clone();").unwrap();
    writeln!(code, "        async move {{").unwrap();
    writeln!(code, "            if body.len() > {policy_name}.max_request_bytes as usize {{ return Err(HandlerError::new(ErrorCode::ResourceExhausted, \"request exceeds generated RPC policy\")); }}").unwrap();
    writeln!(code, "            let request = trace_function(\"protobuf.decode.{service}.{method_name}\", || crate::model::{input}::decode(body.as_slice())).map_err(|error| HandlerError::new(ErrorCode::InvalidRequest, error.to_string()))?;").unwrap();
    writeln!(
        code,
        "            let response = trace_async_function(\"handler.{service}.{method_name}\", service.{rust_method}(request)).await?;"
    )
    .unwrap();
    if method.server_streaming.unwrap_or(false) {
        writeln!(code, "            Ok(try_map_server_stream(response, |response| {{ let encoded = trace_function(\"protobuf.encode.{service}.{method_name}\", || response.encode_to_vec()); if encoded.len() > {policy_name}.max_response_bytes as usize {{ return Err(HandlerError::new(ErrorCode::ResourceExhausted, \"stream item exceeds generated RPC policy\")); }} Ok(encoded) }}))").unwrap();
    } else {
        writeln!(code, "            let encoded = trace_function(\"protobuf.encode.{service}.{method_name}\", || response.encode_to_vec());").unwrap();
        writeln!(code, "            if encoded.len() > {policy_name}.max_response_bytes as usize {{ return Err(HandlerError::new(ErrorCode::ResourceExhausted, \"response exceeds generated RPC policy\")); }}").unwrap();
        writeln!(code, "            Ok(encoded)").unwrap();
    }
    writeln!(code, "        }}").unwrap();
    writeln!(code, "    }});").unwrap();
    Ok(())
}

fn generate_java_method(
    code: &mut String,
    file: &FileDescriptorProto,
    service: &str,
    method: &MethodDescriptorProto,
    types: &HashMap<String, String>,
    policy: &RpcPolicy,
) -> io::Result<()> {
    reject_unsupported_streaming(method)?;
    let name = required(&method.name, "method name")?;
    let input_key = required(&method.input_type, "input type")?;
    let output_key = required(&method.output_type, "output type")?;
    let input = types
        .get(input_key)
        .ok_or_else(|| invalid(format!("unknown input type {input_key}")))?;
    let output = types
        .get(output_key)
        .ok_or_else(|| invalid(format!("unknown output type {output_key}")))?;
    let canonical = canonical_method(file, service, name);
    let id = method_id(&canonical);
    let java_method = lower_camel(name);
    writeln!(
        code,
        "/** Stable wire ID of the {{@code {name}}} RPC. */\npublic static final int {}_METHOD_ID = 0x{id:08X};",
        upper_snake(name)
    )
    .unwrap();
    generate_java_policy_constant(code, name, policy);
    let policy_name = format!("{}_POLICY", upper_snake(name));
    if method.server_streaming.unwrap_or(false) {
        writeln!(code, "/** Opens the credit-controlled {{@code {name}}} server stream. */\npublic Flow.Publisher<{output}> {java_method}({input} request) {{").unwrap();
        writeln!(code, "    byte[] payload = MoonLightTelemetry.traceFunction(\"protobuf.encode.{service}.{name}\", request::toByteArray);").unwrap();
        writeln!(code, "    if (payload.length > {policy_name}.maxRequestBytes()) throw new IllegalArgumentException(\"request exceeds generated RPC policy\");").unwrap();
        writeln!(code, "    Duration callDeadline = deadlineLimit == null ? {policy_name}.timeout() : {policy_name}.effectiveDeadline(deadlineLimit);").unwrap();
        writeln!(code, "    return MoonLightStreams.map(channel.serverStream({}_METHOD_ID, payload, callDeadline, {policy_name}), body -> {{", upper_snake(name)).unwrap();
        writeln!(code, "        if (body.length > {policy_name}.maxResponseBytes()) throw new CompletionException(new IllegalArgumentException(\"response exceeds generated RPC policy\"));").unwrap();
        writeln!(code, "        try {{ return MoonLightTelemetry.traceFunction(\"protobuf.decode.{service}.{name}\", () -> {output}.parseFrom(body)); }}").unwrap();
        writeln!(code, "        catch (com.google.protobuf.InvalidProtocolBufferException error) {{ throw new CompletionException(error); }}").unwrap();
        writeln!(code, "    }});\n}}\n").unwrap();
        return Ok(());
    }
    writeln!(code, "/** Calls {{@code {name}}} asynchronously using this client's deadline. */\npublic CompletableFuture<{output}> {java_method}({input} request) {{").unwrap();
    writeln!(code, "    byte[] payload = MoonLightTelemetry.traceFunction(\"protobuf.encode.{service}.{name}\", request::toByteArray);").unwrap();
    writeln!(code, "    if (payload.length > {policy_name}.maxRequestBytes()) return CompletableFuture.failedFuture(new IllegalArgumentException(\"request exceeds generated RPC policy\"));").unwrap();
    writeln!(code, "    Duration callDeadline = deadlineLimit == null ? {policy_name}.timeout() : {policy_name}.effectiveDeadline(deadlineLimit);").unwrap();
    writeln!(
        code,
        "    return MoonLightChannel.mapFuture(channel.request({}_METHOD_ID, payload, callDeadline, {policy_name}), body -> {{",
        upper_snake(name)
    )
    .unwrap();
    writeln!(code, "        if (body.length > {policy_name}.maxResponseBytes()) throw new CompletionException(new IllegalArgumentException(\"response exceeds generated RPC policy\"));").unwrap();
    writeln!(code, "        try {{ return MoonLightTelemetry.traceFunction(\"protobuf.decode.{service}.{name}\", () -> {output}.parseFrom(body)); }}").unwrap();
    writeln!(code, "        catch (com.google.protobuf.InvalidProtocolBufferException error) {{ throw new CompletionException(error); }}").unwrap();
    writeln!(code, "    }});").unwrap();
    writeln!(code, "}}\n").unwrap();
    writeln!(
        code,
        "/** Calls {{@code {name}}} for every request and preserves input order. */\npublic CompletableFuture<List<{output}>> {java_method}Batch(List<{input}> requests) {{"
    )
    .unwrap();
    writeln!(code, "    Duration callDeadline = deadlineLimit == null ? {policy_name}.timeout() : {policy_name}.effectiveDeadline(deadlineLimit);").unwrap();
    writeln!(code, "    List<MoonLightRequest> calls = requests.stream().map(request -> {{ byte[] payload = request.toByteArray(); if (payload.length > {policy_name}.maxRequestBytes()) throw new IllegalArgumentException(\"request exceeds generated RPC policy\"); return new MoonLightRequest({}_METHOD_ID, payload, callDeadline, {policy_name}); }}).toList();", upper_snake(name)).unwrap();
    writeln!(
        code,
        "    return MoonLightChannel.mapFuture(channel.requestBatch(calls), payloads -> {{"
    )
    .unwrap();
    writeln!(
        code,
        "        List<{output}> responses = new ArrayList<>(payloads.size());"
    )
    .unwrap();
    writeln!(code, "        for (byte[] body : payloads) {{").unwrap();
    writeln!(code, "            if (body.length > {policy_name}.maxResponseBytes()) throw new CompletionException(new IllegalArgumentException(\"response exceeds generated RPC policy\"));").unwrap();
    writeln!(
        code,
        "            try {{ responses.add({output}.parseFrom(body)); }}"
    )
    .unwrap();
    writeln!(code, "            catch (com.google.protobuf.InvalidProtocolBufferException error) {{ throw new CompletionException(error); }}").unwrap();
    writeln!(code, "        }}").unwrap();
    writeln!(code, "        return List.copyOf(responses);").unwrap();
    writeln!(code, "    }});").unwrap();
    writeln!(code, "}}\n").unwrap();
    Ok(())
}

fn rust_policy_name(service: &str, method: &str) -> String {
    format!("{}_{}_POLICY", upper_snake(service), upper_snake(method))
}

fn generate_rust_policy_constant(
    code: &mut String,
    service: &str,
    method: &str,
    policy: &RpcPolicy,
) {
    let name = rust_policy_name(service, method);
    let scopes = policy
        .required_scopes
        .iter()
        .map(|scope| format!("\"{scope}\""))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        code,
        "/// Generated policy for the `{service}/{method}` RPC."
    )
    .unwrap();
    writeln!(code, "pub const {name}: RpcPolicy = RpcPolicy {{").unwrap();
    writeln!(code, "    timeout_ms: {},", policy.timeout_ms).unwrap();
    writeln!(code, "    idle_timeout_ms: {},", policy.idle_timeout_ms).unwrap();
    writeln!(code, "    max_attempts: {},", policy.retry.max_attempts).unwrap();
    writeln!(
        code,
        "    initial_backoff_ms: {},",
        policy.retry.initial_backoff_ms
    )
    .unwrap();
    writeln!(code, "    max_backoff_ms: {},", policy.retry.max_backoff_ms).unwrap();
    writeln!(
        code,
        "    backoff_multiplier_milli: {},",
        policy.retry.multiplier_milli
    )
    .unwrap();
    writeln!(
        code,
        "    idempotency: RpcIdempotency::{:?},",
        policy.idempotency
    )
    .unwrap();
    writeln!(code, "    max_request_bytes: {},", policy.max_request_bytes).unwrap();
    writeln!(
        code,
        "    max_response_bytes: {},",
        policy.max_response_bytes
    )
    .unwrap();
    writeln!(code, "    required_scopes: &[{scopes}],").unwrap();
    writeln!(
        code,
        "    compression: RpcCompression::{:?},",
        policy.compression
    )
    .unwrap();
    writeln!(
        code,
        "    trace_sample_per_million: {},",
        policy.trace_sample_per_million
    )
    .unwrap();
    writeln!(code, "}};\n").unwrap();
}

fn generate_java_policy_constant(code: &mut String, method: &str, policy: &RpcPolicy) {
    let name = format!("{}_POLICY", upper_snake(method));
    let scopes = policy
        .required_scopes
        .iter()
        .map(|scope| format!("\"{scope}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let idempotency = match policy.idempotency {
        Idempotency::Unspecified => "UNSPECIFIED",
        Idempotency::ReadOnly => "READ_ONLY",
        Idempotency::Idempotent => "IDEMPOTENT",
        Idempotency::KeyRequired => "KEY_REQUIRED",
    };
    let compression = match policy.compression {
        CompressionMode::Default => "DEFAULT",
        CompressionMode::Disabled => "DISABLED",
        CompressionMode::Prefer => "PREFER",
        CompressionMode::Required => "REQUIRED",
    };
    writeln!(
        code,
        "/** Generated policy for the {{@code {method}}} RPC. */"
    )
    .unwrap();
    writeln!(
        code,
        "public static final RpcPolicy {name} = new RpcPolicy("
    )
    .unwrap();
    writeln!(code, "    Duration.ofMillis({}),", policy.timeout_ms).unwrap();
    writeln!(code, "    Duration.ofMillis({}),", policy.idle_timeout_ms).unwrap();
    writeln!(
        code,
        "    new RpcPolicy.Retry({}, Duration.ofMillis({}), Duration.ofMillis({}), {}),",
        policy.retry.max_attempts,
        policy.retry.initial_backoff_ms,
        policy.retry.max_backoff_ms,
        policy.retry.multiplier_milli
    )
    .unwrap();
    writeln!(code, "    RpcPolicy.Idempotency.{idempotency},").unwrap();
    writeln!(
        code,
        "    {}, {},",
        policy.max_request_bytes, policy.max_response_bytes
    )
    .unwrap();
    writeln!(code, "    Set.of({scopes}),").unwrap();
    writeln!(code, "    RpcPolicy.Compression.{compression},").unwrap();
    writeln!(code, "    {}", policy.trace_sample_per_million).unwrap();
    writeln!(code, ");\n").unwrap();
}

fn read_descriptor(path: impl AsRef<Path>) -> io::Result<FileDescriptorSet> {
    FileDescriptorSet::decode(fs::read(path)?.as_slice()).map_err(invalid)
}

fn validate_method_ids(descriptor: &FileDescriptorSet) -> io::Result<()> {
    let mut ids = HashSet::new();
    for file in &descriptor.file {
        for service in &file.service {
            let service_name = required(&service.name, "service name")?;
            for method in &service.method {
                let method_name = required(&method.name, "method name")?;
                let canonical = canonical_method(file, service_name, method_name);
                let id = method_id(&canonical);
                if !ids.insert(id) {
                    return Err(invalid(format!(
                        "method ID collision at {canonical}: 0x{id:08X}"
                    )));
                }
            }
        }
        for message in &file.message_type {
            let name = required(&message.name, "message name")?;
            if name.ends_with("Event") {
                let canonical = canonical_event(file, name);
                let id = method_id(&canonical);
                if id == 0 || !ids.insert(id) {
                    return Err(invalid(format!(
                        "event ID collision at {canonical}: 0x{id:08X}"
                    )));
                }
            }
        }
    }
    Ok(())
}

fn java_type_map(descriptor: &FileDescriptorSet) -> io::Result<HashMap<String, String>> {
    let mut result = HashMap::new();
    for file in &descriptor.file {
        let proto_package = file.package.as_deref().unwrap_or("");
        let java_package = java_package(file)?;
        for message in &file.message_type {
            let name = required(&message.name, "message name")?;
            result.insert(
                format!(".{proto_package}.{name}"),
                format!("{java_package}.{name}"),
            );
        }
    }
    Ok(result)
}

fn java_package(file: &FileDescriptorProto) -> io::Result<String> {
    if let Some(package) = file
        .options
        .as_ref()
        .and_then(|options| options.java_package.clone())
    {
        return Ok(package);
    }
    Ok(required(&file.package, "proto package")?.to_owned())
}

fn canonical_method(file: &FileDescriptorProto, service: &str, method: &str) -> String {
    let package = file.package.as_deref().unwrap_or("");
    if package.is_empty() {
        format!("{service}/{method}")
    } else {
        format!("{package}.{service}/{method}")
    }
}

fn canonical_event(file: &FileDescriptorProto, message: &str) -> String {
    let package = file.package.as_deref().unwrap_or("");
    format!("event:{package}.{message}")
}

/// Computes the stable 32-bit FNV-1a wire ID for a canonical method or event name.
pub const fn method_id(name: &str) -> u32 {
    let bytes = name.as_bytes();
    let mut hash = 0x811C_9DC5u32;
    let mut index = 0;
    while index < bytes.len() {
        hash ^= bytes[index] as u32;
        hash = hash.wrapping_mul(0x0100_0193);
        index += 1;
    }
    hash
}

fn rust_message_type(value: Option<&str>) -> io::Result<&str> {
    value
        .ok_or_else(|| invalid("missing message type"))?
        .rsplit('.')
        .next()
        .ok_or_else(|| invalid("invalid message type"))
}

fn reject_unsupported_streaming(method: &MethodDescriptorProto) -> io::Result<()> {
    if method.client_streaming.unwrap_or(false) {
        return Err(invalid(
            "client and bidirectional streaming are not supported yet",
        ));
    }
    Ok(())
}

fn required<'a>(value: &'a Option<String>, field: &str) -> io::Result<&'a str> {
    value
        .as_deref()
        .ok_or_else(|| invalid(format!("missing {field}")))
}

fn snake_case(value: &str) -> String {
    let mut result = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch.is_uppercase() && index > 0 {
            result.push('_');
        }
        result.extend(ch.to_lowercase());
    }
    result
}

fn upper_snake(value: &str) -> String {
    snake_case(value).to_uppercase()
}

fn lower_camel(value: &str) -> String {
    let mut chars = value.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_lowercase().chain(chars).collect()
    })
}

fn upper_camel_words(value: &str) -> String {
    value
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_uppercase().chain(chars).collect()
            })
        })
        .collect()
}

fn invalid(error: impl std::fmt::Display) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn method_ids_are_deterministic() {
        assert_eq!(
            method_id("moonlight.bridge.example.v1.EchoService/Echo"),
            0x237D_FACC
        );
    }

    #[test]
    fn generated_names_follow_language_conventions() {
        assert_eq!(snake_case("GetPlayerData"), "get_player_data");
        assert_eq!(lower_camel("GetPlayerData"), "getPlayerData");
        assert_eq!(upper_snake("GetPlayerData"), "GET_PLAYER_DATA");
    }
}
