[package]
name = "expj-example-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
expj-protocol = { path = "../expj-protocol" }
expj-server = { path = "../expj-server" }
prost.workspace = true

[dev-dependencies]
expj-codegen = { path = "../expj-codegen" }

[build-dependencies]
prost-build.workspace = true
expj-codegen = { path = "../expj-codegen" }
